#ifndef INKEYS_ERASER_GRIP_VISUAL_H
#define INKEYS_ERASER_GRIP_VISUAL_H
// C++预览与HLSL光标共享比例；均以外直径为基准，描边向圆内收。
#define ERASER_GRIP_OUTLINE_RATIO 0.04f
#define ERASER_GRIP_STRIPE_RADIUS_RATIO 0.05f
#define ERASER_GRIP_STRIPE_HALF_HEIGHT_RATIO 0.24f
#define ERASER_GRIP_STRIPE_OFFSET_RATIO 0.12f
#define ERASER_GRIP_OPACITY 0.5f
#define ERASER_GRIP_OUTLINE_CHANNEL (207.0f / 255.0f)
#endif
