<Project>

  <PropertyGroup>
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Platform)'=='Win32'">
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgTriplet>x86-windows-static</VcpkgTriplet>
    <VcpkgInstalledDir>$(MSBuildThisFileDirectory)vcpkg_installed_x86\</VcpkgInstalledDir>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgTriplet>x64-windows-static</VcpkgTriplet>
    <VcpkgInstalledDir>$(MSBuildThisFileDirectory)vcpkg_installed_x64\</VcpkgInstalledDir>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Platform)'=='ARM64'">
    <VcpkgEnableManifest>true</VcpkgEnableManifest>
    <VcpkgTriplet>arm64-windows-static</VcpkgTriplet>
    <VcpkgInstalledDir>$(MSBuildThisFileDirectory)vcpkg_installed_arm64\</VcpkgInstalledDir>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)vcpkg\scripts\buildsystems\msbuild\vcpkg.props" />
</Project>