#pragma once

// Generated by scripts/i18n.ps1 sync. Do not edit manually.

inline constexpr struct I18nKeyRoot
{
    const char* Language = "Language";
    struct Node__Widget
    {
        const char* LnkName = "Widget/LnkName";
    } Widget{};
    struct Node__Operate
    {
        const char* Reset = "Operate/Reset";
        const char* Repair = "Operate/Repair";
        const char* Copy = "Operate/Copy";
        const char* Create = "Operate/Create";
    } Operate{};
    struct Node__UI
    {
        struct Node__UI__Centre
        {
            const char* Select = "UI/Centre/Select";
            const char* SelectClean = "UI/Centre/SelectClean";
            const char* Pen = "UI/Centre/Pen";
            const char* Eraser = "UI/Centre/Eraser";
            const char* Options = "UI/Centre/Options";
        } Centre{};
        struct Node__UI__Pen
        {
            const char* Pen = "UI/Pen/Pen";
            const char* Highlighter = "UI/Pen/Highlighter";
            const char* Thinkness = "UI/Pen/Thinkness";
            const char* Write = "UI/Pen/Write";
            const char* Line = "UI/Pen/Line";
            const char* Square = "UI/Pen/Square";
        } Pen{};
        struct Node__UI__Operate
        {
            const char* Revoke = "UI/Operate/Revoke";
            const char* Recall = "UI/Operate/Recall";
            const char* Freeze = "UI/Operate/Freeze";
            const char* Pierce = "UI/Operate/Pierce";
        } Operate{};
        struct Node__UI__Bar
        {
            struct Node__UI__Bar__BottomDock
            {
                const char* Mode = "UI/Bar/BottomDock/Mode";
                const char* Centered = "UI/Bar/BottomDock/Centered";
            } BottomDock{};
            struct Node__UI__Bar__EraserAttributes
            {
                const char* ClearCanvasLabel = "UI/Bar/EraserAttributes/ClearCanvasLabel";
                const char* ClearCanvasHint = "UI/Bar/EraserAttributes/ClearCanvasHint";
                const char* AutomaticLabel = "UI/Bar/EraserAttributes/AutomaticLabel";
                const char* SensitivityLabel = "UI/Bar/EraserAttributes/SensitivityLabel";
                const char* LowLabel = "UI/Bar/EraserAttributes/LowLabel";
                const char* MediumLabel = "UI/Bar/EraserAttributes/MediumLabel";
                const char* HighLabel = "UI/Bar/EraserAttributes/HighLabel";
                const char* SmallSize = "UI/Bar/EraserAttributes/SmallSize";
                const char* MediumSize = "UI/Bar/EraserAttributes/MediumSize";
                const char* LargeSize = "UI/Bar/EraserAttributes/LargeSize";
                const char* BaseSizeHint = "UI/Bar/EraserAttributes/BaseSizeHint";
                const char* MixedHint = "UI/Bar/EraserAttributes/MixedHint";
                const char* SettingsHint = "UI/Bar/EraserAttributes/SettingsHint";
            } EraserAttributes{};
            struct Node__UI__Bar__MainButtons
            {
                const char* SelectLabel = "UI/Bar/MainButtons/SelectLabel";
                const char* MoveLabel = "UI/Bar/MainButtons/MoveLabel";
                const char* DrawLabel = "UI/Bar/MainButtons/DrawLabel";
                const char* LaserLabel = "UI/Bar/MainButtons/LaserLabel";
                const char* HighlighterLabel = "UI/Bar/MainButtons/HighlighterLabel";
                const char* HardPenLabel = "UI/Bar/MainButtons/HardPenLabel";
                const char* SoftPenLabel = "UI/Bar/MainButtons/SoftPenLabel";
                const char* EraserLabel = "UI/Bar/MainButtons/EraserLabel";
                const char* AreaEraserLabel = "UI/Bar/MainButtons/AreaEraserLabel";
                const char* GeometryLabel = "UI/Bar/MainButtons/GeometryLabel";
                const char* RectangleLabel = "UI/Bar/MainButtons/RectangleLabel";
                const char* StraightLineLabel = "UI/Bar/MainButtons/StraightLineLabel";
                const char* UndoLabel = "UI/Bar/MainButtons/UndoLabel";
                const char* ClearLabel = "UI/Bar/MainButtons/ClearLabel";
                const char* WhiteboardLabel = "UI/Bar/MainButtons/WhiteboardLabel";
                const char* CloseWhiteboardLabel = "UI/Bar/MainButtons/CloseWhiteboardLabel";
                const char* FreezeLabel = "UI/Bar/MainButtons/FreezeLabel";
                const char* EndPresentationLabel = "UI/Bar/MainButtons/EndPresentationLabel";
                const char* SettingsLabel = "UI/Bar/MainButtons/SettingsLabel";
                const char* MoreLabel = "UI/Bar/MainButtons/MoreLabel";
            } MainButtons{};
            struct Node__UI__Bar__DrawAttributes
            {
                const char* BrushLabel = "UI/Bar/DrawAttributes/BrushLabel";
                const char* LaserLabel = "UI/Bar/DrawAttributes/LaserLabel";
                const char* HighlighterLabel = "UI/Bar/DrawAttributes/HighlighterLabel";
                const char* HardPenLabel = "UI/Bar/DrawAttributes/HardPenLabel";
                const char* SoftPenLabel = "UI/Bar/DrawAttributes/SoftPenLabel";
                const char* FreeLineLabel = "UI/Bar/DrawAttributes/FreeLineLabel";
                const char* AnnotationLineLabel = "UI/Bar/DrawAttributes/AnnotationLineLabel";
                const char* HoldThicknessLabel = "UI/Bar/DrawAttributes/HoldThicknessLabel";
                const char* ThicknessFormat = "UI/Bar/DrawAttributes/ThicknessFormat";
                const char* AnnotationUnavailableTitle = "UI/Bar/DrawAttributes/AnnotationUnavailableTitle";
                const char* AnnotationFixedUnsupportedTitle = "UI/Bar/DrawAttributes/AnnotationFixedUnsupportedTitle";
                const char* AnnotationDescription = "UI/Bar/DrawAttributes/AnnotationDescription";
                const char* ThicknessOverflowTitle = "UI/Bar/DrawAttributes/ThicknessOverflowTitle";
                const char* ThicknessOverflowBody = "UI/Bar/DrawAttributes/ThicknessOverflowBody";
            } DrawAttributes{};
            struct Node__UI__Bar__GeometryAttributes
            {
                const char* StraightLineLabel = "UI/Bar/GeometryAttributes/StraightLineLabel";
                const char* RectangleLabel = "UI/Bar/GeometryAttributes/RectangleLabel";
            } GeometryAttributes{};
            struct Node__UI__Bar__ColorPicker
            {
                const char* RedChannelLabel = "UI/Bar/ColorPicker/RedChannelLabel";
                const char* GreenChannelLabel = "UI/Bar/ColorPicker/GreenChannelLabel";
                const char* BlueChannelLabel = "UI/Bar/ColorPicker/BlueChannelLabel";
                const char* OpacityLabel = "UI/Bar/ColorPicker/OpacityLabel";
                const char* HoldColorLabel = "UI/Bar/ColorPicker/HoldColorLabel";
            } ColorPicker{};
            struct Node__UI__Bar__Diagnostics
            {
                const char* FrameRateFormat = "UI/Bar/Diagnostics/FrameRateFormat";
                const char* FrameRateUnavailable = "UI/Bar/Diagnostics/FrameRateUnavailable";
            } Diagnostics{};
            struct Node__UI__Bar__Errors
            {
                const char* TransparentBackgroundWarning = "UI/Bar/Errors/TransparentBackgroundWarning";
            } Errors{};
        } Bar{};
    } UI{};
    struct Node__Dialogs
    {
        struct Node__Dialogs__Common
        {
            const char* TipsTitle = "Dialogs/Common/TipsTitle";
            const char* ErrorTitle = "Dialogs/Common/ErrorTitle";
            const char* OK = "Dialogs/Common/OK";
            const char* Cancel = "Dialogs/Common/Cancel";
            const char* Yes = "Dialogs/Common/Yes";
            const char* No = "Dialogs/Common/No";
        } Common{};
        struct Node__Dialogs__EndPresentation
        {
            const char* Body = "Dialogs/EndPresentation/Body";
        } EndPresentation{};
        struct Node__Dialogs__WindowCreationFailed
        {
            const char* Body = "Dialogs/WindowCreationFailed/Body";
        } WindowCreationFailed{};
        struct Node__Dialogs__UpdateModuleUnavailable
        {
            const char* Body = "Dialogs/UpdateModuleUnavailable/Body";
        } UpdateModuleUnavailable{};
        struct Node__Dialogs__CloseInkeys
        {
            const char* Body = "Dialogs/CloseInkeys/Body";
        } CloseInkeys{};
        struct Node__Dialogs__Crash
        {
            const char* Body = "Dialogs/Crash/Body";
        } Crash{};
    } Dialogs{};
    struct Node__SettingsUI
    {
        const char* N = "SettingsUI/N";
        struct Node__SettingsUI__Home
        {
            const char* N = "SettingsUI/Home/N";
            const char* Prompt = "SettingsUI/Home/Prompt";
            const char* Developer = "SettingsUI/Home/Developer";
            const char* Group = "SettingsUI/Home/Group";
            const char* GroupE = "SettingsUI/Home/GroupE";
            const char* BilibiliChannel = "SettingsUI/Home/BilibiliChannel";
            const char* FeedBack = "SettingsUI/Home/FeedBack";
        } Home{};
        struct Node__SettingsUI__Language
        {
            const char* N = "SettingsUI/Language/N";
            struct Node__SettingsUI__Language__UI
            {
                const char* N = "SettingsUI/Language/UI/N";
                const char* Select = "SettingsUI/Language/UI/Select";
                const char* SelectE = "SettingsUI/Language/UI/SelectE";
                struct Node__SettingsUI__Language__UI__Language
                {
                    const char* en_US = "SettingsUI/Language/UI/Language/en-US";
                    const char* zh_CN = "SettingsUI/Language/UI/Language/zh-CN";
                    const char* zh_TW = "SettingsUI/Language/UI/Language/zh-TW";
                } Language{};
                const char* Warn = "SettingsUI/Language/UI/Warn";
            } UI{};
        } Language{};
        struct Node__SettingsUI__Configuration
        {
            const char* N = "SettingsUI/Configuration/N";
            struct Node__SettingsUI__Configuration__Clean
            {
                const char* N = "SettingsUI/Configuration/Clean/N";
                const char* Enable = "SettingsUI/Configuration/Clean/Enable";
                const char* EnableE = "SettingsUI/Configuration/Clean/EnableE";
            } Clean{};
            struct Node__SettingsUI__Configuration__CanvasSave
            {
                const char* N = "SettingsUI/Configuration/CanvasSave/N";
                const char* Enable = "SettingsUI/Configuration/CanvasSave/Enable";
                const char* EnableE = "SettingsUI/Configuration/CanvasSave/EnableE";
                struct Node__SettingsUI__Configuration__CanvasSave__SaveTime
                {
                    const char* N = "SettingsUI/Configuration/CanvasSave/SaveTime/N";
                    const char* E = "SettingsUI/Configuration/CanvasSave/SaveTime/E";
                    const char* K_1d = "SettingsUI/Configuration/CanvasSave/SaveTime/1d";
                    const char* K_3d = "SettingsUI/Configuration/CanvasSave/SaveTime/3d";
                    const char* K_5d = "SettingsUI/Configuration/CanvasSave/SaveTime/5d";
                    const char* K_10d = "SettingsUI/Configuration/CanvasSave/SaveTime/10d";
                    const char* K_30d = "SettingsUI/Configuration/CanvasSave/SaveTime/30d";
                    const char* Never = "SettingsUI/Configuration/CanvasSave/SaveTime/Never";
                } SaveTime{};
            } CanvasSave{};
        } Configuration{};
        struct Node__SettingsUI__Version
        {
            const char* N = "SettingsUI/Version/N";
            struct Node__SettingsUI__Version__ManualUpdate
            {
                const char* N = "SettingsUI/Version/ManualUpdate/N";
                const char* ManualUpdate = "SettingsUI/Version/ManualUpdate/ManualUpdate";
            } ManualUpdate{};
            struct Node__SettingsUI__Version__LimitUpdate
            {
                const char* N = "SettingsUI/Version/LimitUpdate/N";
                const char* Info = "SettingsUI/Version/LimitUpdate/Info";
            } LimitUpdate{};
            struct Node__SettingsUI__Version__Inkeys3Update
            {
                const char* N = "SettingsUI/Version/Inkeys3Update/N";
                const char* Download = "SettingsUI/Version/Inkeys3Update/Download";
            } Inkeys3Update{};
            const char* VersionTip = "SettingsUI/Version/VersionTip";
            struct Node__SettingsUI__Version__Info
            {
                const char* N = "SettingsUI/Version/Info/N";
                const char* ReleaseVersion = "SettingsUI/Version/Info/ReleaseVersion";
                const char* ReleaseDate = "SettingsUI/Version/Info/ReleaseDate";
                const char* ReleaseArch = "SettingsUI/Version/Info/ReleaseArch";
                const char* ReleaseTag = "SettingsUI/Version/Info/ReleaseTag";
                const char* DebugTag = "SettingsUI/Version/Info/DebugTag";
                const char* ManualBuild = "SettingsUI/Version/Info/ManualBuild";
                const char* AutoBuild = "SettingsUI/Version/Info/AutoBuild";
                const char* CICDInfo = "SettingsUI/Version/Info/CICDInfo";
            } Info{};
            struct Node__SettingsUI__Version__UserInfo
            {
                const char* N = "SettingsUI/Version/UserInfo/N";
                const char* CopyUserId = "SettingsUI/Version/UserInfo/CopyUserId";
                const char* UserId = "SettingsUI/Version/UserInfo/UserId";
            } UserInfo{};
            struct Node__SettingsUI__Version__Repair
            {
                const char* N = "SettingsUI/Version/Repair/N";
                const char* RepairSoftware = "SettingsUI/Version/Repair/RepairSoftware";
                const char* RepairSoftwareE = "SettingsUI/Version/Repair/RepairSoftwareE";
                const char* RepairArch = "SettingsUI/Version/Repair/RepairArch";
            } Repair{};
            struct Node__SettingsUI__Version__Update
            {
                const char* N = "SettingsUI/Version/Update/N";
                const char* AutoUpate = "SettingsUI/Version/Update/AutoUpate";
                const char* ChannelTip = "SettingsUI/Version/Update/ChannelTip";
                struct Node__SettingsUI__Version__Update__Channel
                {
                    const char* N = "SettingsUI/Version/Update/Channel/N";
                    const char* LTS = "SettingsUI/Version/Update/Channel/LTS";
                    const char* Insider = "SettingsUI/Version/Update/Channel/Insider";
                    const char* Canary = "SettingsUI/Version/Update/Channel/Canary";
                } Channel{};
                struct Node__SettingsUI__Version__Update__Arch
                {
                    const char* N = "SettingsUI/Version/Update/Arch/N";
                    const char* E = "SettingsUI/Version/Update/Arch/E";
                    const char* K_64 = "SettingsUI/Version/Update/Arch/64";
                    const char* K_32 = "SettingsUI/Version/Update/Arch/32";
                    const char* Arm64 = "SettingsUI/Version/Update/Arch/Arm64";
                } Arch{};
            } Update{};
        } Version{};
        struct Node__SettingsUI__CICD
        {
            const char* N = "SettingsUI/CICD/N";
            const char* Repository = "SettingsUI/CICD/Repository";
            const char* Branch = "SettingsUI/CICD/Branch";
            const char* Submitter = "SettingsUI/CICD/Submitter";
            const char* BuildTime = "SettingsUI/CICD/BuildTime";
            const char* BuildSystem = "SettingsUI/CICD/BuildSystem";
            const char* BuildSystemVersion = "SettingsUI/CICD/BuildSystemVersion";
            const char* RunnerImageSystem = "SettingsUI/CICD/RunnerImageSystem";
            const char* RunnerImageVersion = "SettingsUI/CICD/RunnerImageVersion";
            const char* MSBuildVersion = "SettingsUI/CICD/MSBuildVersion";
        } CICD{};
        struct Node__SettingsUI__Regular
        {
            const char* N = "SettingsUI/Regular/N";
            struct Node__SettingsUI__Regular__StartUp
            {
                const char* N = "SettingsUI/Regular/StartUp/N";
                const char* AutoStart = "SettingsUI/Regular/StartUp/AutoStart";
                const char* AutoStartE = "SettingsUI/Regular/StartUp/AutoStartE";
                const char* LoadingAnimation = "SettingsUI/Regular/StartUp/LoadingAnimation";
                struct Node__SettingsUI__Regular__StartUp__Link
                {
                    const char* N = "SettingsUI/Regular/StartUp/Link/N";
                    const char* E = "SettingsUI/Regular/StartUp/Link/E";
                    const char* More = "SettingsUI/Regular/StartUp/Link/More";
                } Link{};
            } StartUp{};
            struct Node__SettingsUI__Regular__Appearance
            {
                const char* N = "SettingsUI/Regular/Appearance/N";
                const char* AnimationEnable = "SettingsUI/Regular/Appearance/AnimationEnable";
                const char* AnimationEnableE = "SettingsUI/Regular/Appearance/AnimationEnableE";
                const char* AnimationRate = "SettingsUI/Regular/Appearance/AnimationRate";
                const char* AnimationRateE = "SettingsUI/Regular/Appearance/AnimationRateE";
                const char* EdgeLighting = "SettingsUI/Regular/Appearance/EdgeLighting";
                const char* EdgeLightingE = "SettingsUI/Regular/Appearance/EdgeLightingE";
                const char* DynamicEdgeLighting = "SettingsUI/Regular/Appearance/DynamicEdgeLighting";
                const char* DynamicEdgeLightingE = "SettingsUI/Regular/Appearance/DynamicEdgeLightingE";
                struct Node__SettingsUI__Regular__Appearance__Theme
                {
                    const char* N = "SettingsUI/Regular/Appearance/Theme/N";
                    const char* E = "SettingsUI/Regular/Appearance/Theme/E";
                    const char* Skip1 = "SettingsUI/Regular/Appearance/Theme/Skip1";
                    const char* Skip2 = "SettingsUI/Regular/Appearance/Theme/Skip2";
                    const char* Skip3 = "SettingsUI/Regular/Appearance/Theme/Skip3";
                    const char* Skip4 = "SettingsUI/Regular/Appearance/Theme/Skip4";
                } Theme{};
                struct Node__SettingsUI__Regular__Appearance__BarZoom
                {
                    const char* N = "SettingsUI/Regular/Appearance/BarZoom/N";
                    const char* E = "SettingsUI/Regular/Appearance/BarZoom/E";
                    const char* Ind = "SettingsUI/Regular/Appearance/BarZoom/Ind";
                } BarZoom{};
                struct Node__SettingsUI__Regular__Appearance__SettingUIScale
                {
                    const char* N = "SettingsUI/Regular/Appearance/SettingUIScale/N";
                    const char* E = "SettingsUI/Regular/Appearance/SettingUIScale/E";
                    const char* Ind = "SettingsUI/Regular/Appearance/SettingUIScale/Ind";
                } SettingUIScale{};
            } Appearance{};
            struct Node__SettingsUI__Regular__Behavior
            {
                const char* N = "SettingsUI/Regular/Behavior/N";
                struct Node__SettingsUI__Regular__Behavior__TopWindow
                {
                    const char* N = "SettingsUI/Regular/Behavior/TopWindow/N";
                    const char* E = "SettingsUI/Regular/Behavior/TopWindow/E";
                    const char* K_100ms = "SettingsUI/Regular/Behavior/TopWindow/100ms";
                    const char* K_500ms = "SettingsUI/Regular/Behavior/TopWindow/500ms";
                    const char* K_1s = "SettingsUI/Regular/Behavior/TopWindow/1s";
                    const char* K_3s = "SettingsUI/Regular/Behavior/TopWindow/3s";
                    const char* K_5s = "SettingsUI/Regular/Behavior/TopWindow/5s";
                    const char* K_10s = "SettingsUI/Regular/Behavior/TopWindow/10s";
                    const char* K_30s = "SettingsUI/Regular/Behavior/TopWindow/30s";
                } TopWindow{};
                const char* RightClickClose = "SettingsUI/Regular/Behavior/RightClickClose";
                const char* RightClickCloseE = "SettingsUI/Regular/Behavior/RightClickCloseE";
                const char* DrawingRetract = "SettingsUI/Regular/Behavior/DrawingRetract";
                const char* ErasingRetract = "SettingsUI/Regular/Behavior/ErasingRetract";
                const char* DraggingRetract = "SettingsUI/Regular/Behavior/DraggingRetract";
                const char* CheckingRetract = "SettingsUI/Regular/Behavior/CheckingRetract";
                const char* CheckingRetractE = "SettingsUI/Regular/Behavior/CheckingRetractE";
            } Behavior{};
            struct Node__SettingsUI__Regular__Tentative
            {
                const char* N = "SettingsUI/Regular/Tentative/N";
                struct Node__SettingsUI__Regular__Tentative__SafeMode
                {
                    const char* N = "SettingsUI/Regular/Tentative/SafeMode/N";
                    const char* E = "SettingsUI/Regular/Tentative/SafeMode/E";
                    const char* Mode1 = "SettingsUI/Regular/Tentative/SafeMode/Mode1";
                    const char* Mode2 = "SettingsUI/Regular/Tentative/SafeMode/Mode2";
                    const char* Mode3 = "SettingsUI/Regular/Tentative/SafeMode/Mode3";
                    const char* Mode4 = "SettingsUI/Regular/Tentative/SafeMode/Mode4";
                } SafeMode{};
            } Tentative{};
        } Regular{};
        struct Node__SettingsUI__Draw
        {
            const char* N = "SettingsUI/Draw/N";
            struct Node__SettingsUI__Draw__Effect
            {
                const char* N = "SettingsUI/Draw/Effect/N";
                struct Node__SettingsUI__Draw__Effect__Device
                {
                    const char* N = "SettingsUI/Draw/Effect/Device/N";
                    const char* E = "SettingsUI/Draw/Effect/Device/E";
                    const char* Touch = "SettingsUI/Draw/Effect/Device/Touch";
                    const char* MousePen = "SettingsUI/Draw/Effect/Device/MousePen";
                } Device{};
            } Effect{};
            struct Node__SettingsUI__Draw__Eraser
            {
                const char* N = "SettingsUI/Draw/Eraser/N";
                const char* Automatic = "SettingsUI/Draw/Eraser/Automatic";
                struct Node__SettingsUI__Draw__Eraser__Input
                {
                    const char* MouseLeft = "SettingsUI/Draw/Eraser/Input/MouseLeft";
                    const char* MouseRight = "SettingsUI/Draw/Eraser/Input/MouseRight";
                    const char* Touch = "SettingsUI/Draw/Eraser/Input/Touch";
                    const char* PenTip = "SettingsUI/Draw/Eraser/Input/PenTip";
                    const char* PenTail = "SettingsUI/Draw/Eraser/Input/PenTail";
                } Input{};
                struct Node__SettingsUI__Draw__Eraser__Kind
                {
                    const char* Fixed = "SettingsUI/Draw/Eraser/Kind/Fixed";
                    const char* Speed = "SettingsUI/Draw/Eraser/Kind/Speed";
                } Kind{};
                const char* ResponseFor = "SettingsUI/Draw/Eraser/ResponseFor";
                struct Node__SettingsUI__Draw__Eraser__Response
                {
                    const char* Auto = "SettingsUI/Draw/Eraser/Response/Auto";
                    const char* ScreenPen = "SettingsUI/Draw/Eraser/Response/ScreenPen";
                    const char* Digitizer = "SettingsUI/Draw/Eraser/Response/Digitizer";
                } Response{};
                struct Node__SettingsUI__Draw__Eraser__TouchArea
                {
                    const char* N = "SettingsUI/Draw/Eraser/TouchArea/N";
                    const char* E = "SettingsUI/Draw/Eraser/TouchArea/E";
                } TouchArea{};
            } Eraser{};
        } Draw{};
        struct Node__SettingsUI__Experimental
        {
            struct Node__SettingsUI__Experimental__ConsoleOutput
            {
                struct Node__SettingsUI__Experimental__ConsoleOutput__TouchArea
                {
                    const char* N = "SettingsUI/Experimental/ConsoleOutput/TouchArea/N";
                    const char* E = "SettingsUI/Experimental/ConsoleOutput/TouchArea/E";
                } TouchArea{};
                struct Node__SettingsUI__Experimental__ConsoleOutput__PptCOM
                {
                    const char* N = "SettingsUI/Experimental/ConsoleOutput/PptCOM/N";
                    const char* E = "SettingsUI/Experimental/ConsoleOutput/PptCOM/E";
                } PptCOM{};
                struct Node__SettingsUI__Experimental__ConsoleOutput__Draw3
                {
                    const char* N = "SettingsUI/Experimental/ConsoleOutput/Draw3/N";
                    const char* E = "SettingsUI/Experimental/ConsoleOutput/Draw3/E";
                } Draw3{};
            } ConsoleOutput{};
        } Experimental{};
        struct Node__SettingsUI__PlugIn
        {
            const char* N = "SettingsUI/PlugIn/N";
            struct Node__SettingsUI__PlugIn__PPTHelper
            {
                const char* N = "SettingsUI/PlugIn/PPTHelper/N";
                const char* E = "SettingsUI/PlugIn/PPTHelper/E";
                const char* VersionError = "SettingsUI/PlugIn/PPTHelper/VersionError";
                const char* Solve = "SettingsUI/PlugIn/PPTHelper/Solve";
                const char* Sync = "SettingsUI/PlugIn/PPTHelper/Sync";
                const char* Reset = "SettingsUI/PlugIn/PPTHelper/Reset";
                const char* Tip = "SettingsUI/PlugIn/PPTHelper/Tip";
                const char* Warn = "SettingsUI/PlugIn/PPTHelper/Warn";
                const char* Error = "SettingsUI/PlugIn/PPTHelper/Error";
                struct Node__SettingsUI__PlugIn__PPTHelper__BasicLogic
                {
                    const char* N = "SettingsUI/PlugIn/PPTHelper/BasicLogic/N";
                    const char* LoadPage = "SettingsUI/PlugIn/PPTHelper/BasicLogic/LoadPage";
                    const char* LoadPageE = "SettingsUI/PlugIn/PPTHelper/BasicLogic/LoadPageE";
                } BasicLogic{};
                struct Node__SettingsUI__PlugIn__PPTHelper__WidgetDisplay
                {
                    const char* N = "SettingsUI/PlugIn/PPTHelper/WidgetDisplay/N";
                    const char* BottomBoth = "SettingsUI/PlugIn/PPTHelper/WidgetDisplay/BottomBoth";
                    const char* MiddleBoth = "SettingsUI/PlugIn/PPTHelper/WidgetDisplay/MiddleBoth";
                    const char* BottomMiddle = "SettingsUI/PlugIn/PPTHelper/WidgetDisplay/BottomMiddle";
                } WidgetDisplay{};
                struct Node__SettingsUI__PlugIn__PPTHelper__WidgetPosition
                {
                    const char* N = "SettingsUI/PlugIn/PPTHelper/WidgetPosition/N";
                    const char* Reset = "SettingsUI/PlugIn/PPTHelper/WidgetPosition/Reset";
                    const char* Remember = "SettingsUI/PlugIn/PPTHelper/WidgetPosition/Remember";
                } WidgetPosition{};
                struct Node__SettingsUI__PlugIn__PPTHelper__WidgetScale
                {
                    const char* N = "SettingsUI/PlugIn/PPTHelper/WidgetScale/N";
                    const char* Ind = "SettingsUI/PlugIn/PPTHelper/WidgetScale/Ind";
                    struct Node__SettingsUI__PlugIn__PPTHelper__WidgetScale__Page
                    {
                        const char* BottomSideBoth = "SettingsUI/PlugIn/PPTHelper/WidgetScale/Page/BottomSideBoth";
                        const char* MiddleSideBoth = "SettingsUI/PlugIn/PPTHelper/WidgetScale/Page/MiddleSideBoth";
                    } Page{};
                    struct Node__SettingsUI__PlugIn__PPTHelper__WidgetScale__State
                    {
                        const char* BottomSideMiddle = "SettingsUI/PlugIn/PPTHelper/WidgetScale/State/BottomSideMiddle";
                    } State{};
                } WidgetScale{};
                struct Node__SettingsUI__PlugIn__PPTHelper__Tentative
                {
                    const char* N = "SettingsUI/PlugIn/PPTHelper/Tentative/N";
                    const char* CloseWpp = "SettingsUI/PlugIn/PPTHelper/Tentative/CloseWpp";
                    const char* CloseWppE = "SettingsUI/PlugIn/PPTHelper/Tentative/CloseWppE";
                    const char* AutoTakeOver = "SettingsUI/PlugIn/PPTHelper/Tentative/AutoTakeOver";
                    const char* AutoTakeOverE = "SettingsUI/PlugIn/PPTHelper/Tentative/AutoTakeOverE";
                    const char* AutoTakeOverOnce = "SettingsUI/PlugIn/PPTHelper/Tentative/AutoTakeOverOnce";
                    const char* AutoTakeOverOnceE = "SettingsUI/PlugIn/PPTHelper/Tentative/AutoTakeOverOnceE";
                    const char* AutoTakeOverExpand = "SettingsUI/PlugIn/PPTHelper/Tentative/AutoTakeOverExpand";
                    const char* EnablePageButtonLongPress = "SettingsUI/PlugIn/PPTHelper/Tentative/EnablePageButtonLongPress";
                } Tentative{};
            } PPTHelper{};
            struct Node__SettingsUI__PlugIn__SuperTop
            {
                const char* N = "SettingsUI/PlugIn/SuperTop/N";
                const char* E = "SettingsUI/PlugIn/SuperTop/E";
                const char* Warn = "SettingsUI/PlugIn/SuperTop/Warn";
                struct Node__SettingsUI__PlugIn__SuperTop__Capability
                {
                    const char* N = "SettingsUI/PlugIn/SuperTop/Capability/N";
                    const char* SuperTop = "SettingsUI/PlugIn/SuperTop/Capability/SuperTop";
                    const char* SuperTopE1 = "SettingsUI/PlugIn/SuperTop/Capability/SuperTopE1";
                    const char* SuperTopE2 = "SettingsUI/PlugIn/SuperTop/Capability/SuperTopE2";
                    const char* Indicator = "SettingsUI/PlugIn/SuperTop/Capability/Indicator";
                    const char* IndicatorE = "SettingsUI/PlugIn/SuperTop/Capability/IndicatorE";
                } Capability{};
            } SuperTop{};
            struct Node__SettingsUI__PlugIn__DesktopDrawpadBlocker
            {
                const char* N = "SettingsUI/PlugIn/DesktopDrawpadBlocker/N";
                const char* E = "SettingsUI/PlugIn/DesktopDrawpadBlocker/E";
            } DesktopDrawpadBlocker{};
            struct Node__SettingsUI__PlugIn__LnkHelper
            {
                const char* N = "SettingsUI/PlugIn/LnkHelper/N";
                const char* E = "SettingsUI/PlugIn/LnkHelper/E";
                struct Node__SettingsUI__PlugIn__LnkHelper__Capability
                {
                    const char* N = "SettingsUI/PlugIn/LnkHelper/Capability/N";
                    const char* FixLnk = "SettingsUI/PlugIn/LnkHelper/Capability/FixLnk";
                    const char* FixLnkE = "SettingsUI/PlugIn/LnkHelper/Capability/FixLnkE";
                } Capability{};
                struct Node__SettingsUI__PlugIn__LnkHelper__Expansion
                {
                    const char* N = "SettingsUI/PlugIn/LnkHelper/Expansion/N";
                    const char* CreateLnk = "SettingsUI/PlugIn/LnkHelper/Expansion/CreateLnk";
                    const char* CreateLnkE = "SettingsUI/PlugIn/LnkHelper/Expansion/CreateLnkE";
                } Expansion{};
            } LnkHelper{};
        } PlugIn{};
        struct Node__SettingsUI__Component
        {
            const char* N = "SettingsUI/Component/N";
        } Component{};
        struct Node__SettingsUI__HotKey
        {
            const char* N = "SettingsUI/HotKey/N";
            const char* E = "SettingsUI/HotKey/E";
        } HotKey{};
        struct Node__SettingsUI__Community
        {
            const char* N = "SettingsUI/Community/N";
        } Community{};
        struct Node__SettingsUI__Sponsor
        {
            const char* N = "SettingsUI/Sponsor/N";
        } Sponsor{};
        struct Node__SettingsUI__RestartSoftware
        {
            const char* N = "SettingsUI/RestartSoftware/N";
        } RestartSoftware{};
        struct Node__SettingsUI__ExitSoftware
        {
            const char* N = "SettingsUI/ExitSoftware/N";
        } ExitSoftware{};
        struct Node__SettingsUI__DebugSoftware
        {
            const char* N = "SettingsUI/DebugSoftware/N";
        } DebugSoftware{};
        struct Node__SettingsUI__Update
        {
            const char* Check = "SettingsUI/Update/Check";
            struct Node__SettingsUI__Update__Channel
            {
                const char* LTS = "SettingsUI/Update/Channel/LTS";
                const char* Insider = "SettingsUI/Update/Channel/Insider";
                const char* Dev = "SettingsUI/Update/Channel/Dev";
                const char* Canary = "SettingsUI/Update/Channel/Canary";
                const char* Other = "SettingsUI/Update/Channel/Other";
            } Channel{};
            const char* NotStarted = "SettingsUI/Update/NotStarted";
            const char* ObtainInformation = "SettingsUI/Update/ObtainInformation";
            const char* InformationFail = "SettingsUI/Update/InformationFail";
            const char* InformationDamage = "SettingsUI/Update/InformationDamage";
            const char* InformationUnStandardized = "SettingsUI/Update/InformationUnStandardized";
            const char* Downloading = "SettingsUI/Update/Downloading";
            const char* DownloadFail = "SettingsUI/Update/DownloadFail";
            const char* DownloadDamage = "SettingsUI/Update/DownloadDamage";
            const char* Restart = "SettingsUI/Update/Restart";
            const char* Latest = "SettingsUI/Update/Latest";
            const char* Newer = "SettingsUI/Update/Newer";
            const char* New = "SettingsUI/Update/New";
            const char* Repair = "SettingsUI/Update/Repair";
            const char* ManualDownload = "SettingsUI/Update/ManualDownload";
            const char* UpdateNow = "SettingsUI/Update/UpdateNow";
        } Update{};
    } SettingsUI{};
} I18nKey{};
