# 这是用于构建混合 C++ (MSVC v143) 和 C# (.NET Framework) 项目的 GitHub Actions 工作流程

name: Inkeys Build

on:
  push:
    branches:
      - dev #
      - main
      - insider # 在 main 和 insider 分支 push 时触发
permissions:
  actions: write

jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [Win32, x64, ARM64]
      fail-fast: false
    runs-on: windows-latest

    steps:
      # step 1
    - name: Checkout code 
      uses: actions/checkout@v4

    # step 2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup .NET Framework 4.0
      shell: pwsh
      run: |
        $zipPath = ".\ActionsRes\v4.0.zip"
        $tempPath = ".\temp"
        $targetParent = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework"
        # 解压 zip 到临时目录
        Expand-Archive -Path $zipPath -DestinationPath $tempPath
        # 创建目标父目录（如果不存在）
        if (!(Test-Path $targetParent)) {
          New-Item -Path $targetParent -ItemType Directory | Out-Null
        }
        # 拷贝整个 v4.0 文件夹到目标父目录下
        Copy-Item -Path "$tempPath\v4.0" -Destination $targetParent -Recurse -Force
    - name: Restore NuGet packages
      run: nuget restore "智绘教.sln"

    - name: Build Inkeys
      run: msbuild "智绘教.sln" /p:Configuration=Release /p:Platform=${{ matrix.platform }} /verbosity:minimal
      shell: cmd

    # step 3
    - name: Upload exe[unsigned] artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform == 'Win32' && 'Inkeys[Unsigned]' || 
                  matrix.platform == 'x64' && 'Inkeys64[Unsigned]' || 
                  matrix.platform == 'ARM64' && 'InkeysArm64[Unsigned]' }}
        path: |
          ${{ (matrix.platform == 'Win32' && './Release/Inkeys.exe') || 
              (matrix.platform == 'x64' && './x64/Release/Inkeys.exe') || 
              (matrix.platform == 'ARM64' && './ARM64/Release/Inkeys.exe') }}

  signature:
    name: Signature
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Inkeys[Unsigned]
        uses: actions/download-artifact@v4
        with:
          name: Inkeys[Unsigned]
          path: tmp/win32
      - name: Download Inkeys64[Unsigned]
        uses: actions/download-artifact@v4
        with:
          name: Inkeys64[Unsigned]
          path: tmp/x64
      - name: Download InkeysArm64[Unsigned]
        uses: actions/download-artifact@v4
        with:
          name: InkeysArm64[Unsigned]
          path: tmp/arm64

      - name: Prepare signpath zip folder
        run: |
          mkdir send_zip
          copy tmp\win32\Inkeys.exe send_zip\Inkeys.exe
          copy tmp\x64\Inkeys.exe send_zip\Inkeys64.exe
          copy tmp\arm64\Inkeys.exe send_zip\InkeysArm64.exe
          
      - name: Upload Signpath[unsigned]
        id: upload-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: Signpath[unsigned]
          path: send_zip/

      - name: Sign with SignPath
        id: signpath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '95390269-627b-496d-8127-fc47de793284'
          project-slug: 'Inkeys'
          signing-policy-slug: 'release-signing'
          github-artifact-id: '${{ steps.upload-unsigned.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: './signed-artifacts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Prepare update folder
        run: |
          mkdir update
          mkdir update64
          mkdir updateArm64
          copy signed-artifacts\Inkeys.exe update\Inkeys.exe
          copy signed-artifacts\Inkeys64.exe update64\Inkeys.exe
          copy signed-artifacts\InkeysArm64.exe updateArm64\Inkeys.exe

      - name: Upload Inkeys
        uses: actions/upload-artifact@v4
        with:
          name: Inkeys
          path: update\Inkeys.exe
      - name: Upload Inkeys64
        uses: actions/upload-artifact@v4
        with:
          name: Inkeys64
          path: update64\Inkeys.exe
      - name: Upload InkeysArm64
        uses: actions/upload-artifact@v4
        with:
          name: InkeysArm64
          path: updateArm64\Inkeys.exe

      - name: Clean Up
        shell: pwsh
        env:
          ARTIFACT_NAMES: 'Inkeys[Unsigned],Inkeys64[Unsigned],InkeysArm64[Unsigned],Signpath[unsigned]'
        run: |
          # 拆分目标 artifact 列表
          $names = "${env:ARTIFACT_NAMES}".Split(',')

          # 获取 artifact 元信息
          $repo = "${{ github.repository }}"
          $url = "https://api.github.com/repos/$repo/actions/artifacts?per_page=100"
          $headers = @{ Authorization = "Bearer ${{ secrets.GITHUB_TOKEN }}" }
          $response = Invoke-RestMethod -Uri $url -Headers $headers

          # 批量删除
          foreach ($name in $names) {
            $artifact = $response.artifacts | Where-Object { $_.name -eq $name }
            if ($null -ne $artifact) {
              Write-Host "Deleting artifact: $($artifact.name) $($artifact.id)"
              $delete_url = "https://api.github.com/repos/$repo/actions/artifacts/$($artifact.id)"
              Invoke-RestMethod -Uri $delete_url -Headers $headers -Method Delete
            } else {
              Write-Host "Not found: $name"
            }
          }

  package:
    name: Package
    runs-on: windows-latest
    needs: signature

    steps:
      - name: Download Inkeys
        uses: actions/download-artifact@v4
        with:
          name: Inkeys
          path: tmp/win32
      - name: Download Inkeys64
        uses: actions/download-artifact@v4
        with:
          name: Inkeys64
          path: tmp/x64
      - name: Download InkeysArm64
        uses: actions/download-artifact@v4
        with:
          name: InkeysArm64
          path: tmp/arm64 

      - name: Prepare signpath zip folder
        run: |
          mkdir Inkeys
          mkdir Inkeys64
          mkdir InkeysArm64
          copy tmp\win32\Inkeys.exe Inkeys\Inkeys.exe
          copy tmp\x64\Inkeys.exe Inkeys64\Inkeys.exe
          copy tmp\arm64\Inkeys.exe InkeysArm64\Inkeys.exe

      - name: Compressed update package 1
        run: |
          Compress-Archive -Path .\Inkeys\Inkeys.exe -DestinationPath .\InkeysUpdate2025====!.zip -CompressionLevel Optimal
      - name: Compressed update package 2
        run: |
          Compress-Archive -Path .\Inkeys64\Inkeys.exe -DestinationPath .\InkeysUpdate2025====!64.zip -CompressionLevel Optimal
      - name: Compressed update package 3
        run: |
          Compress-Archive -Path .\InkeysArm64\Inkeys.exe -DestinationPath .\InkeysUpdate2025====!Arm64.zip -CompressionLevel Optimal

      - name: Prepare configuration information 1
        shell: pwsh
        run: |
          $exeFile = 'Inkeys\Inkeys.exe'
          $uploadFile = 'InkeysUpdate2025====!.zip'
          $out = 'ci.txt'
          
          $md5    = (Get-FileHash -Path $exeFile -Algorithm MD5   ).Hash
          $sha256 = (Get-FileHash -Path $exeFile -Algorithm SHA256).Hash
          $size   = (Get-Item $uploadFile).Length

          "[Inkeys]`nMD5: $md5`nSHA256: $sha256`nEXE_SIZE: $size" | Add-Content $out -Encoding UTF8
      - name: Prepare configuration information 2
        shell: pwsh
        run: |
          $exeFile = 'Inkeys64\Inkeys.exe'
          $uploadFile = 'InkeysUpdate2025====!64.zip'
          $out = 'ci.txt'
          
          $md5    = (Get-FileHash -Path $exeFile -Algorithm MD5   ).Hash
          $sha256 = (Get-FileHash -Path $exeFile -Algorithm SHA256).Hash
          $size   = (Get-Item $uploadFile).Length

          "[Inkeys64]`nMD5: $md5`nSHA256: $sha256`nEXE_SIZE: $size" | Add-Content $out -Encoding UTF8
      - name: Prepare configuration information 3
        shell: pwsh
        run: |
          $exeFile = 'InkeysArm64\Inkeys.exe'
          $uploadFile = 'InkeysUpdate2025====!Arm64.zip'
          $out = 'ci.txt'
          
          $md5    = (Get-FileHash -Path $exeFile -Algorithm MD5   ).Hash
          $sha256 = (Get-FileHash -Path $exeFile -Algorithm SHA256).Hash
          $size   = (Get-Item $uploadFile).Length

          "[InkeysArm64]`nMD5: $md5`nSHA256: $sha256`nEXE_SIZE: $size" | Add-Content $out -Encoding UTF8
      
      - name: Write Tips
        shell: pwsh
        run: |
          $content = @"
          软件使用方法：
          1. Inkeys.exe 运行文件放置于一个空的文件夹内（exe 名称不能包含非英文字符）
          2. 双击 Inkeys.exe 运行即可
          
          提示：
          设置桌面快捷方式和开机启动可以进软件选项界面中设置。
          有疑问吐槽建议等等，加Q群618720802一起讨论，或咨询作者QQ2685549821。
          
          -----
          
          How to use the software:
          1. Inkeys.exe runtime file is placed in an empty folder (exe name can not contain non-English characters)
          2. Double-click Inkeys.exe to run.
          
          Tips: 
          Set desktop shortcuts and boot up can be set into the software options interface.
          If you have any questions, comments, suggestions, etc., through the software feedback channel for feedback, or consult the author alan-crl@foxmail.com.
          "@

          Set-Content -Path Tips.txt -Value $content -Encoding UTF8
      - name: Prepare Tips
        run: |
          copy Tips.txt Inkeys\Tips.txt
          copy Tips.txt Inkeys64\Tips.txt
          copy Tips.txt InkeysArm64\Tips.txt

      - name: Compressed release package 1
        run: |
          Compress-Archive -Path .\Inkeys -DestinationPath .\[版本][32位]Inkeys2025====!.zip -CompressionLevel Optimal
      - name: Compressed release package 2
        run: |
          Compress-Archive -Path .\Inkeys64 -DestinationPath .\[版本][64位]Inkeys2025====!.zip -CompressionLevel Optimal
      - name: Compressed release package 3
        run: |
          Compress-Archive -Path .\InkeysArm64 -DestinationPath .\[版本][Arm64]Inkeys2025====!.zip -CompressionLevel Optimal

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: |
            InkeysUpdate2025====!.zip
            InkeysUpdate2025====!64.zip
            InkeysUpdate2025====!Arm64.zip
            ci.txt
            [版本][32位]Inkeys2025====!.zip
            [版本][64位]Inkeys2025====!.zip
            [版本][Arm64]Inkeys2025====!.zip