# 这是用于构建混合 C++ (MSVC v143) 和 C# (.NET Framework) 项目的 GitHub Actions 工作流程

name: Inkeys Build

on:
  push:
    branches:
      - main
      - insider # 在 main 和 insider 分支 push 时触发

jobs:
  build:
    strategy:
      matrix:
        platform: [Win32, x64, ARM64] # 
      fail-fast: false

    runs-on: windows-latest

    steps:
      # step 1
    - name: Checkout code 
      uses: actions/checkout@v4

    # step 2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Setup .NET Framework 4.0
      shell: pwsh
      run: |
        $zipPath = ".\ActionsRes\v4.0.zip"
        $tempPath = ".\temp"
        $targetParent = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework"
        # 解压 zip 到临时目录
        Expand-Archive -Path $zipPath -DestinationPath $tempPath
        # 创建目标父目录（如果不存在）
        if (!(Test-Path $targetParent)) {
          New-Item -Path $targetParent -ItemType Directory | Out-Null
        }
        # 拷贝整个 v4.0 文件夹到目标父目录下
        Copy-Item -Path "$tempPath\v4.0" -Destination $targetParent -Recurse -Force
    - name: Restore NuGet packages
      run: nuget restore "智绘教.sln"

    - name: Build Inkeys
      run: msbuild "智绘教.sln" /p:Configuration=Release /p:Platform=${{ matrix.platform }} /verbosity:minimal
      shell: cmd

    # step 3
    - name: Upload exe[unsigned] artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform == 'Win32' && 'Inkeys[Unsigned]' || 
                  matrix.platform == 'x64' && 'Inkeys64[Unsigned]' || 
                  matrix.platform == 'ARM64' && 'InkeysArm64[Unsigned]' }}
        path: |
          ${{ (matrix.platform == 'Win32' && './Release/Inkeys.exe') || 
              (matrix.platform == 'x64' && './x64/Release/Inkeys.exe') || 
              (matrix.platform == 'ARM64' && './ARM64/Release/Inkeys.exe') }}

  signature:
    name: Signature
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Inkeys[Unsigned]
        uses: actions/download-artifact@v4
        with:
          name: Inkeys[Unsigned]
          path: tmp/win32
      - name: Download Inkeys64[Unsigned]
        uses: actions/download-artifact@v4
        with:
          name: Inkeys64[Unsigned]
          path: tmp/x64
      - name: Download InkeysArm64[Unsigned]
        uses: actions/download-artifact@v4
        with:
          name: InkeysArm64[Unsigned]
          path: tmp/arm64

      - name: Prepare signpath zip folder
        run: |
          mkdir send_zip
          copy tmp\win32\Inkeys.exe send_zip\Inkeys.exe
          copy tmp\x64\Inkeys.exe send_zip\Inkeys64.exe
          copy tmp\arm64\Inkeys.exe send_zip\InkeysArm64.exe
          
      - name: Upload signpath[unsigned]
        id: upload-unsigned
        uses: actions/upload-artifact@v4
        with:
          name: signpath[unsigned]
          path: send_zip/

      - name: Sign with SignPath
        id: signpath
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '95390269-627b-496d-8127-fc47de793284'
          project-slug: 'Inkeys'
          signing-policy-slug: 'release_certificate_2025'
          github-artifact-id: '${{ steps.upload-unsigned.outputs.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: './signed-artifacts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Prepare update folder
        run: |
          mkdir update
          mkdir update64
          mkdir updateArm64
          copy signed-artifacts\Inkeys.exe update\Inkeys.exe
          copy signed-artifacts\Inkeys64.exe update64\Inkeys.exe
          copy signed-artifacts\InkeysArm64.exe updateArm64\Inkeys.exe

      - name: Upload Inkeys
        uses: actions/upload-artifact@v4
        with:
          name: Inkeys
          path: update\Inkeys.exe
      - name: Upload Inkeys64
        uses: actions/upload-artifact@v4
        with:
          name: Inkeys64
          path: update64\Inkeys.exe
      - name: Upload InkeysArm64
        uses: actions/upload-artifact@v4
        with:
          name: InkeysArm64
          path: updateArm64\Inkeys.exe